/*
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2017 JSQLParser
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 6.1_2 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTCOLUMN = 3;
  public int JJTTABLE = 4;
  public int JJTWITHITEM = 5;
  public int JJTEXPRESSION = 6;
  public int JJTCASEWHENEXPRESSION = 7;
  public int JJTFUNCTION = 8;
  public int JJTSUBSELECT = 9;


  public String[] jjtNodeName = {
    "Statement",
    "void",
    "Statements",
    "Column",
    "Table",
    "WithItem",
    "Expression",
    "CaseWhenExpression",
    "Function",
    "SubSelect",
  };
}
/* JavaCC - OriginalChecksum=f081470383bd08946d1aede2db424429 (do not edit this line) */
